/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Graph graph = new SingleGraph("eeeeeeeeeeeeeee");
        graph.addNode("A");
        graph.addNode("B");
    }
}
